#!/usr/bin/env python3

# Copyright 2017 Chris Diamand
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import argparse
import os

import version

logger = None
MAX_LOG_SIZE = 4 * 1024 * 1024 # 4 MB


def init_logging(logfile):
    import logging
    import logging.handlers
    import time

    global logger
    logger = logging.getLogger(version.NAME)
    logger.setLevel(logging.DEBUG)

    stderr_logger = logging.StreamHandler()
    stderr_logger.setLevel(logging.INFO)
    logger.addHandler(stderr_logger)

    try:
        os.makedirs(os.path.dirname(logfile))
    except:
        pass
    file_logger = logging.handlers.RotatingFileHandler(logfile,
                                                       maxBytes=MAX_LOG_SIZE,
                                                       backupCount=5)
    file_logger.setLevel(logging.DEBUG)
    file_fmt = logging.Formatter("%(asctime)s:%(module)13s: %(message)s")
    file_fmt.converter = time.gmtime
    file_logger.setFormatter(file_fmt)

    logger.addHandler(file_logger)
    logger.debug("--- [starting] ---")


def parse_args():
    ap = argparse.ArgumentParser()

    ap.add_argument("-l", "--logfile",
                    default=os.path.expanduser("~/.{0}/{0}.log".format(version.NAME)))

    return ap.parse_args()


def main():
    args = parse_args()
    init_logging(args.logfile)

    import backend
    import gui

    iface = backend.Interface()
    app = gui.MixerApp(iface)
    app.MainLoop()


if __name__ == "__main__":
    main()
